from django.conf.urls import url
from django.views.generic import TemplateView
from website import views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="index.html"),
        name='index'),
    url(r'^services$', TemplateView.as_view(template_name="services.html"),
        name='services'),
    url(r'^equipment$', TemplateView.as_view(template_name="equipment.html"),
        name='equipment'),
    url(r'^contact$', TemplateView.as_view(template_name="contact.html"),
        name='contact'),
    url(r'^external$', TemplateView.as_view(template_name="external.html"),
        name='external'),
    url(r'^join$', TemplateView.as_view(template_name="join.html"),
        name='join'),
    url(r'^crew$', TemplateView.as_view(template_name="crew.html"),
        name='crew'),
    url(r'^hots$', TemplateView.as_view(template_name="hots.html"),
        name='hots'),
    url(r'^alumni$', TemplateView.as_view(template_name="alumni.html"),
        name='alumni'),
    url(r'^events$', TemplateView.as_view(template_name="events.html"),
        name='events'),
    url(r'^events70$', TemplateView.as_view(template_name="events-1970.html"),
        name='events70'),
    url(r'^events80$', TemplateView.as_view(template_name="events-1980.html"),
        name='events80'),
    url(r'^events90$', TemplateView.as_view(template_name="events-1990.html"),
        name='events90'),
    url(r'^events00$', TemplateView.as_view(template_name="events-2000.html"),
        name='events00'),
    url(r'^timelapse$', TemplateView.as_view(template_name="timelapse.html"),
        name='timelapse'),
    url(r'^accolades$', TemplateView.as_view(template_name="accolades.html"),
        name='accolades'),
    url(r'^styletest$', TemplateView.as_view(template_name="styletest.html"),
        name='styletest'),
    url(r'^signup$', views.signup, name='signup'),
    url(r'^request$', TemplateView.as_view(template_name="request.html"),
        name='request')
]
